### ISSUE TITLE
something about Preprocess_true_boxes

### ISSUE THREAD

**Issue by yuto3o** [aloyschen/tensorflow-yolo3#5]
From line 99 to 113 in dataReader.py, the process of IOU is only related to wh of boxes. As I known, when we calculate the value of IOU between two boxes, all of x, y, w, h should be used. Is there anything wrong with me?

**Comment by aloyschen** [comment]
The iou Coordinate System of true box and anchor box is center,  so the x, y is w / 2, h / 2

**Comment by yuto3o** [comment]
I have understood this process, but still thank you

**Comment by yuto3o** [comment]
Nine anchors are compared with the same bounding box at each time. So the coordinates (e.g., x and y) are ignored in the way of calculating iou, because x and y don't affect the sort of iou values. In other words, only w and h affect their sort.

**Comment by yuto3o** [comment]
> @aloyschen Thanks for your effort. I have the same questions. In your way of calculating iou:
> intersect_min = np.maximum(boxes_min, anchors_min)
> intersect_max = np.minimum(boxes_max, anchors_max)
> intersect_wh = np.maximum(intersect_max - intersect_min, 0.)
> intersect_area = intersect_wh[..., 0] * intersect_wh[..., 1]
> it seems that you assume the center of anchors and the center of the true_boxes are same. Is that right?
> @yuto3o Hi, how do you understand this process, can u share some hints? Thank u!
Nine anchors are compared with the same bounding box at each time. So the coordinates (e.g., x and y) are ignored in the way of calculating iou, because x and y don't affect the sort of iou values. In other words, only w and h affect their sort.

**Comment by Runist** [comment]
@XhqGlorry11 I think beacause anchors just have w and h, and you don't need know xy. You just put there two boxes in same center, to get iou so that you can know which anchor is more simlar the true boxes
